# Generated by Django 2.1.7 on 2019-05-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dream', '0002_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
