# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-07 08:58
from __future__ import unicode_literals

import Dream.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='Dream/', validators=[Dream.models.FileValidator(content_types='application/x-dosexec')]),
        ),
    ]
